// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckLogin():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function PerformFetch(arg1:main.FetchRequest):Promise<main.FetchResponse>;
